services:

  u1:
    image: suleymanddonmez/u1:latest
    container_name: u1
    restart: always
    networks:
      - u1_network
    expose:
      - 3001

  u2:
    image: suleymanddonmez/u2:latest
    container_name: u2
    restart: always
    networks:
      - u2_network
    expose:
      - 3002

  u3:
    image: suleymanddonmez/u3:latest
    container_name: u3
    restart: always
    networks:
      - u3_network
    expose:
      - 3003

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - u1_network
      - u2_network
      - u3_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

networks:
  u1_network:
  u2_network:
  u3_network: